// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-west-1",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_kR9CJEeQp",
    "aws_user_pools_web_client_id": "4j3f8up4l4fhsab3d51rm2p0au",
    "aws_content_delivery_bucket": "quizapp-20181228212757-hostingbucket",
    "aws_content_delivery_bucket_region": "eu-west-1",
    "aws_content_delivery_url": "https://dr2o1k60fqj5m.cloudfront.net"
};


export default awsmobile;
